AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lavanda-feed-show-serverless
  Sample SAM Template for lavanda-feed-show-serverless
Globals:
  Function:
    Timeout: 180
    MemorySize: 400
Resources:
  # DonTorrentFunction:
  #   Type: AWS::Serverless::Function 
  #   Properties:
  #     FunctionName: lavanda-feed-show-dontorrent
  #     CodeUri: lavanda-feed-shows
  #     Handler: es.lavanda.feed.show.DonTorrentApp::handleRequest
  #     Runtime: java11
  #     Role: arn:aws:iam::836783797541:role/service-role/lavanda-feed-show-role-4pdw316k   
  #     Events:
  #       Schedule1:
  #         Type: Schedule
  #         Properties:
  #           Schedule: cron(0 0 * * ? *)
  #     EventInvokeConfig:
  #       DestinationConfig:
  #         OnSuccess:
  #           Type: SQS
  #           Destination: arn:aws:sqs:eu-west-1:836783797541:feed-shows-pro
          # OnFailure:
          #   Type: Lambda
          #   Destination: !GetAtt DestinationLambda.Arn      
  PctMixFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: lavanda-feed-show-pctmix
      CodeUri: lavanda-feed-shows
      Handler: es.lavanda.feed.show.PctmixApp::handleRequest
      Runtime: java11
      Role: arn:aws:iam::836783797541:role/lavanda-feed-shows-role   
      # Events:
      #   Schedule1:
      #     Type: Schedule
      #     Properties:
      #       Schedule: cron(0 0 * * ? *)     
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: SQS
            Destination: arn:aws:sqs:eu-west-1:836783797541:feed-shows-pro
Outputs:
  # DonTorrentFunction:
  #   Description: "Don Torrent Lambda Function ARN"
  #   Value: !GetAtt DonTorrentFunction.Arn
  PctMixFunction:
    Description: "Pctmix Lambda Function ARN"
    Value: !GetAtt PctMixFunction.Arn
  